spring:
  application:
    name: transaction-server
  rabbitmq:
    host: localhost
    port: 5672
    connection-timeout: 2000
server:
  port: 8888
---
spring:
  rabbitmq:
    host: rabbitmq
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/